# 28.08.23 - HOMEWORK 1
## DUE DATE: 04.09.23
## NO LATE SUBMISSION

Submissions on google classroom


1 - Rastgele bir zar atıldığında her bir yüzün gelme olasılığını hesaplayın. Ardından bir madeni para atıldığında yazı veya tura gelme olasılığını hesaplayın. Bu iki olayın bir arada gerçekleşme olasılığını nasıl bulursunuz?

Zarın 6 yüzü vardır. Herbir yüzünün gelme ihtimali = 1/6
Paranın yazı veya tura gelme ihtimali = 1/2
Her iki olayın bir arada gerçekleşme ihtimali bu ihtimallerin çarpımıyla bulunur.
(1/2)*(1/6)=1/12

In [1]:
dice=[1,2,3,4,5,6]
coin=['Yazı','Tura']


for i in (dice):
    print("Zarın" , i , "gelme ihtimali =",1/len(dice))
for i in (coin):
    print("Paranın" , i , "gelme ihtimali =",1/len(coin))

print("İki olayın bir arada gerçekleşme ihtimali =",1/(len(dice)*len(coin)))
    

Zarın 1 gelme ihtimali = 0.16666666666666666
Zarın 2 gelme ihtimali = 0.16666666666666666
Zarın 3 gelme ihtimali = 0.16666666666666666
Zarın 4 gelme ihtimali = 0.16666666666666666
Zarın 5 gelme ihtimali = 0.16666666666666666
Zarın 6 gelme ihtimali = 0.16666666666666666
Paranın Yazı gelme ihtimali = 0.5
Paranın Tura gelme ihtimali = 0.5
İki olayın bir arada gerçekleşme ihtimali = 0.08333333333333333


2 - Bir torbada 5 kırmızı, 7 mavi ve 8 yeşil top bulunmaktadır. Rastgele bir top çekildiğinde mavi gelme olasılığını hesaplayın.

In [2]:
kırmızı=['K','K','K','K','K']
mavi=['M','M','M','M','M','M','M']
yeşil=['Y','Y','Y','Y','Y','Y','Y','Y']
torba = kırmızı+mavi+yeşil
print('Mavi gelme ihtimali =',len(mavi)/len(torba))

Mavi gelme ihtimali = 0.35


3 - Verilen bir veri kümesi için ortalama, medyan ve mod değerlerini bulun:
> 12,15,14,10,10,13,17,19,10,14,14,15

In [3]:
import numpy as np
from scipy import stats

veriKumesi = np.array([12,15,14,10,10,13,17,19,10,14,14,15])

veriKumesi.sort()
ortalama = sum(veriKumesi) / len(veriKumesi) 
medyan = np.median(veriKumesi)
mod = stats.mode(veriKumesi)

print('Ortalama =', ortalama)
print('Medyan =', medyan)
print('Mod =', mod.mode[0])

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


Ortalama = 13.583333333333334
Medyan = 14.0
Mod = 10


4 - Yukarıdaki verilen veri kümesi için standart sapma hesaplayın

In [4]:
stdSapma = np.std(veriKumesi)

print("Standart sapma = ", stdSapma)

Standart sapma =  2.6912925436591904


5 - Sola/sağa çarpık dağılım nedir? Python kullanarak, bir veri kümesinin dağılımının sola mı yoksa sağa mı çarpık olduğunu nasıl tespit edersiniz?

Verinin çarpıklık (skewness) değeri verinin simetrisinin tanımıdır.

Bir dağılım simetrik, sağa veya sola çarpık olabilir. Verinin:

Tek bir tepesi, ortadan bölündüğünde sağda ve solda simetrik bir görüntüsü varsa dağılım simetriktir.
Kuyruğu sağa doğru uzuyorsa, dağılım sağa çarpık veya pozitiftir.
Kuyruğu sola doğru uzuyorsa, dağılım sola çarpık veya negatiftir.

Yani pythonda çarpıklık değerine bakarak tespitte bulunabiliriz. Değer 0'dan büyükse dizi sağa çarpıktır.

6 - Python'da NumPy kütüphanesini nasıl içe aktarırsınız?

In [5]:
import numpy as np

7 - Numpy arrayleri pythondaki list yapısına kıyasla çok daha verimlidir ve matematiksel işlemler söz konusu olduğunda sıklıkla ndarrayleri tercih ederiz. Bunun sebebi nedir? Sebepleri en az 5 maddeyle açıklayınız.

Yanıt: 

1.Numpy arrayleri, aynı veri türünden elemanlar içerirken Python listeleri farklı veri türlerini içerebilir.  Aynı veri türü içermesi, bellekte daha düzenli bir veri düzenlemesi sağlar..

2. Numpy yüksek performanslı kütüphaneleriyle uygulandığı için vektörleştirilmiş operasyonları destekler. Bu sayede pythondaki döngülerle işlem yapmaktan çok daha hızlıdır.

3. Numpy, veriyi daha az bellek alanında depolayarak veri bellek yönetimini daha verimli hale getirir. Ayrıca, numpy arrayleri bellekte düzgün bir şekilde yerleştirildiği için bellek erişimi daha hızlıdır.

4. Numpy, farklı şekillere sahip arrayler arasında yayma (broadcasting) yapabilme yeteneğine sahiptir. Bu, arraylerinizi farklı şekil ve boyutlarda olsa bile matematiksel işlemler yaparken kullanımı kolaylaştırır.

5. Numpy, istatistiksel hesaplamalar, lineer cebir operasyonları, rastgele sayı üretimi gibi birçok optimize edilmiş fonksiyonu içerir. Bu fonksiyonlar daha hızlı ve doğru sonuçlar sağlar.

8 - 0’dan 100'e kadar olan sayıları içeren bir NumPy dizisi oluşturun. Ardından bu diziyi 10x10 matrise dönüştürün.


In [6]:
import numpy as np

arr = np.arange(0,100)

arr = arr.reshape(10,10)

print (arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


9 - Yukarıda oluşturduğunuz matrisin her bir sütununun ortalamasını bulun.

In [7]:
np.mean(arr, axis=0)

array([45., 46., 47., 48., 49., 50., 51., 52., 53., 54.])

10 - `np.arange(16).reshape(4, 4)` ile oluşturulan bir matrisi yatay olarak iki eşit parçaya ayırın (split).


In [8]:
arrSplit = np.arange(16).reshape(4,4)
np.split(arrSplit,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

11 - Aşağıdaki gibi bir NumPy dizisi oluşturun:
>     arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]),
* Bu dizi üzerinden ilk iki satırı ve ilk iki sütunu dilimleyerek (slice) yeni bir alt dizi elde edin. 
* Yukarıda verilen arr dizisinden, sadece tek sayılardan oluşan bir dizi elde edin.

In [9]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
arrFirst = arr[:2, :2]
print("İLk iki satır ve ilk iki sütundan oluşan alt dizi:", arrFirst)


arrSecond = list()
oddNums = (arr % 2 == 1)
arrSecond = arr[oddNums]
print("Tek sayılardan oluşan alt dizi:",arrSecond)

İLk iki satır ve ilk iki sütundan oluşan alt dizi: [[1 2]
 [5 6]]
Tek sayılardan oluşan alt dizi: [ 1  3  5  7  9 11 13 15]


12 - Aşağıda verilen iki diziyi dikey olarak üst üste ekleyin (stack):
> a = np.array([1, 2, 3])

> b = np.array([4, 5, 6])

In [10]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
print("New stack:")
np.vstack((a,b))

New stack:


array([[1, 2, 3],
       [4, 5, 6]])

13 - Aşağıdaki gibi iki farklı dizi oluşturun:
> arr1 = np.array([[1, 2], [3, 4]])

> arr2 = np.array([[5, 6]])

arr2 dizisini arr1 dizisinin altına ekleyin ve elde edilen bu yeni dizi üzerinden son satırı ve son sütunu dilimleyin.

In [11]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6]])

arr_stack = np.vstack((arr1,arr2))
arr_sliced = arr_stack[-1:,-1:]

print("Sliced Array:",arr_sliced)

Sliced Array: [[6]]


14 - `np.arange(30).reshape(5, 6)` ile oluşturulan bir matrisin ilk 3 satırını alın ve bu 3 satırı 2 eşit parçaya ayırın.


In [12]:
matx = np.arange(30).reshape(5, 6)

sliced_matrix = matx[:3,:]

half_matrix = np.hsplit(sliced_matrix,2)

print("İlk üç satırı alınan matrix:",sliced_matrix,"\n\n","İkiye bölünmüş hali:",half_matrix)

İlk üç satırı alınan matrix: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

 İkiye bölünmüş hali: [array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17]])]


15 -  `np.arange(1, 17).reshape(4, 4)` dizi üzerinden her satırın ikinci elemanını alarak yeni bir dizi oluşturun. Ardından bu yeni diziyi orijinal dizinin sağına ekleyin

In [13]:
arr = np.arange(1, 17).reshape(4, 4)

arr1 = arr[:,1].reshape(4,1)

newArr = np.hstack((arr,arr1))

print("Yeni dizi: \n", newArr)

Yeni dizi: 
 [[ 1  2  3  4  2]
 [ 5  6  7  8  6]
 [ 9 10 11 12 10]
 [13 14 15 16 14]]
